### ISSUE TITLE
loop limit square root of N

### ISSUE THREAD

**Issue by Paul-Browne** [p4nu/prime-checker-api#1]
You only need to check numbers less than or equal to the square root of N for primeness :)
https://github.com/p4nu/prime-checker-api/blob/65a3418dbb6c3a60eb69a396bcd46f1cff43b8fb/util/isPrime.js#L15

could be...
```js
const rootN = Math.sqrt(n);
for (let i = 2; i <= rootN; i++) { 
```

**Comment by p4nu** [comment]
Thanks for the comment! I will try and test your suggestion just in case 😉

**Comment by p4nu** [comment]
It works! 👍
